{% set name = "pydantic" %}
{% set version = "1.10.6" %}
{% set repo_url = "https://github.com/samuelcolvin/pydantic" %}
{% set docs_url = "https://pydantic-docs.helpmanual.io" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf95adb0d1671fc38d8c43dd921ad5814a735e7d9b4d9e437c088002863854fd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - typing-extensions >=4.2.0

test:
  imports:
    - {{ name }}

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
    - samuelcolvin
    - dgasmith
    - davidbrochart
